developer_search/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("search.urls")),
    path("", include("pwa.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path("", views.index, name="search"),
    path("credits", views.credits, name="credits"),
]

search/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .helpers import perform_search, manage_theme
from urllib.parse import urlencode
from django.conf import settings


# Create your views here.


def index(request):
    """ The page where users can search """

    url_params = {}
    query = request.GET.get("q", "")
    start_index = request.GET.get("start")
    search_data = perform_search(query, start_index=start_index)

    return render(request, "search/index.html", {
        "query": query,
        **search_data,
        **manage_theme(request, query, start_index),
    })


def credits(request):
    """ Credits to all the open source projects used in DevSearch """

    # Data of each open source project included
    projects = {
        'Django': {
            'description': 'Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design',
            'project_link': 'https://github.com/django/django',
            'license_type': 'BSD',
            'license_link': 'https://github.com/django/django/blob/master/LICENSE.python',
            'copyright': 'Copyright (c) Django Software Foundation and individual contributors.',
        },
        'Materialize': {
            'description': 'Materialize, a CSS Framework based on Material Design',
            'project_link': 'https://github.com/Dogfalo/materialize',
            'license_type': 'MIT',
            'license_link': 'https://github.com/Dogfalo/materialize/blob/v1-dev/LICENSE',
            'copyright': 'Copyright (c) 2014-2019 Materialize',
        },

        'google-api-python-client': {
            'description': "The official Python client library for Google's discovery based APIs.",
            'project_link': 'https://github.com/googleapis/google-api-python-client',
            'license_type': 'Apache',
            'license_link': 'https://github.com/googleapis/google-api-python-client/blob/master/LICENSE',
            'copyright': ' Copyright 2014 Google Inc. All Rights Reserved.',
        },

        'rapidfuzz': {
            'description': 'Rapid fuzzy string matching in Python and C++ using the Levenshtein Distance',
            'project_link': 'https://github.com/maxbachmann/rapidfuzz',
            'license_type': 'MIT',
            'license_link': 'https://github.com/maxbachmann/rapidfuzz/blob/master/LICENSE',
            'copyright': 'Copyright © 2020 maxbachmann. Copyright © 2011 Adam Cohen',
        },

        'django-heroku': {
            'description': 'Django library for Heroku applications that ensures a seamless deployment and development experience.',
            'project_link': 'https://github.com/heroku/django-heroku',
            'license_type': 'BSD',
            'license_link': 'https://github.com/heroku/django-heroku/blob/master/LICENSE',
            'copyright': 'Copyright (c) 2017, Heroku. All rights reserved.',
        },
        'django-htmlmin': {
            'description': 'django-html is an HTML minifier for Python, with full support for HTML 5',
            'project_link': 'https://github.com/cobrateam/django-htmlmin',
            'license_type': 'BSD',
            'license_link': 'https://github.com/cobrateam/django-htmlmin/blob/master/LICENSE',
            'copyright': 'Copyright (c) 2012, django-htmlmin authors. All rights reserved.',
        },

        'django-htmlmin': {
            'description': 'django-html is an HTML minifier for Python, with full support for HTML 5',
            'project_link': 'https://github.com/cobrateam/django-htmlmin',
            'license_type': 'BSD',
            'license_link': 'https://github.com/cobrateam/django-htmlmin/blob/master/LICENSE',
            'copyright': 'Copyright (c) 2012, django-htmlmin authors. All rights reserved.',
        },

         'tldextract': {
            'description': 'Accurately separate the TLD from the registered domain and subdomains of a URL, using the Public Suffix List.',
            'project_link': 'https://github.com/john-kurkowski/tldextract',
            'license_type': 'BSD',
            'license_link': 'https://github.com/john-kurkowski/tldextract/blob/master/LICENSE',
            'copyright': 'Copyright (c) 2019, John Kurkowski. All rights reserved.',
        },

         'python-decouple': {
            'description': 'Decouple helps you to organize your settings so that you can change parameters without having to redeploy your app.',
            'project_link': 'https://github.com/henriquebastos/python-decouple/',
            'license_type': 'MIT',
            'license_link': 'https://github.com/henriquebastos/python-decouple/blob/master/LICENSE',
            'copyright': 'Copyright (c) 2013 Henrique Bastos',
        },

        'gunicorn': {
            'description': "gunicorn 'Green Unicorn' is a WSGI HTTP Server for UNIX, fast clients and sleepy applications",
            'project_link': 'https://github.com/benoitc/gunicorn',
            'license_type': 'MIT',
            'license_link': 'https://github.com/benoitc/gunicorn/blob/master/LICENSE',
            'copyright': '2009-2018 (c) Benoît Chesneau. 2009-2015 (c) Paul J. Davis ',
        },
    }

    return render(request, "search/credits.html", {
        'projects': projects,
        **manage_theme(request, "",0),
    })

search/templates/offline.html
{% extends 'search/base.html' %}
{% load static %}

{% block css %}

    <link rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'light-variables.min.css' %}">
    <link rel="stylesheet" href="{% static 'index.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

{% endblock css %}

{% block body %}

    <div style="height:70vh!important;width:100%;display:flex;align-items:center;justify-content:center" >
    
        <div class="center-align">

            <div class="row">
                <h2>DevSearch</h2>
            </div>

            <div class="row"></div>
            <div class="row"></div>
            
            <div 
                class="center-align grey-text text-darken-2">

                <div class="row"> 
                    <i class="material-icons md-48">emoji_nature</i>
                </div>
                <div>
                    <span class="light-text med-font">You are offline</span>
                </div>
            </div>
            
            <div class="center-align grey-text text-darken-2">
                <span> 
                    <small class="light-text">Try connecting to a network</small>
                </span>
            </div>

        </div>

    </div>



{% endblock body %}

{% block footer %}{% endblock footer %}

search/templates/search/base.html
{% load static %}
{% load pwa %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="google-site-verification" content="xrEq34SiNE9z1rg-b5rC9csvIk4YJunG0KMzQNgRIUk" />
    <meta name="description" content="A search engine for developers to find Github Repos, youtube tutorials, online courses, and documentation faster.">
    <meta name="robots" content="nofollow" />
    <meta name="keywords" content="devsearch, developer search, developer search engine," />

    {% if not theme or theme == "light" %}
      <meta name="theme-color" content="#370e42">
    {% elif theme == "dark" %}
      <meta name="theme-color" content="#222">
    {% endif %}

    {% progressive_web_app_meta %}

    {% comment %} Favicon {% endcomment %}
    <link rel="icon" 
      type="image/png" 
      href="{% static 'short-logo.png' %}">

    <title>{% block title %} DevSearch - A Search Engine for Developers {% endblock title %}</title>

    {% block css %}
      {% comment %} Materialize css {% endcomment %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">


      {% comment %} No "theme" session is set, so follow the preferred color scheme set by system {% endcomment %}
      {% if not theme %} 
         <link rel="stylesheet" 
              href="{% static 'light-variables.min.css' %}"
              media="(prefers-color-scheme: no-preference), (prefers-color-scheme: light)" >
        <link 
          rel="stylesheet" 
          href="{% static 'dark-variables.min.css' %}" 
          media="(prefers-color-scheme: dark)" >

      {% comment %} Only include `light-variables` css, if session "theme" is set to "light" {% endcomment %}
      {% elif theme == "light" %}
        
        <link rel="stylesheet" href="{% static 'light-variables.min.css' %}" >

      {% comment %} Only include `dark-variables` css, if session "theme" is set to "dark" {% endcomment %}
      {% elif theme == "dark"%}
      
        <link rel="stylesheet" href="{% static 'dark-variables.min.css' %}" >
      
      {% endif %}

        <link rel="stylesheet" href="{% static 'index.min.css' %}" >
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% endblock css %}

  </head>
  <body class="major-mono">
    {% comment %} Main content {% endcomment %}
    <main>
      {% block body %}
      {% endblock body %}
    </main>


  {% comment %} Footer {% endcomment %}
  {% block footer %}

    <footer class="page-footer z-depth-1">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5>  
                  <a href="/">
                    <span class="purple-text text-lighten-3">Dev</span><span class="white-text">Search</span>
                  </a>
                </h5>
                <p class="grey-text text-lighten-4">The search engine for developers by a developer. </p>
              </div>

              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">About</h5>
                <ul>
                  <li><a target="_blank" rel="noopener" class="grey-text text-lighten-3" href="https://github.com/zaidmukaddam/developer-search/blob/main/README.md#devsearch">About the project</a></li>
                  <li><a target="_blank" rel="noopener" class="grey-text text-lighten-3" href="https://www.github.com/zaidmukaddam">About me</a></li>
                  <li><a class="grey-text text-lighten-3" href="{% url 'search:credits' %}">Credits</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
              
              <div class="left">
                <p>
                  Copyright &copy; &nbsp;<script>document.write( new Date().getFullYear() )</script>&nbsp;
                </p>
                <p>
                  Created by Zaid Mukaddam
                </p>
              </div>

              <div class="right">
                <a 
                  id="theme-toggle"
                  href="#!"
                  class="clickable grey-text text-lighten-2">
                  ...
                </a>
              </div>
            </div>
          </div>
        </footer>

  {% endblock footer %}

    {% block js %}
        {% comment %} Materialize Js {% endcomment %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script type="text/javascript">const overide_preferred_color_scheme="{{theme_session_set|safe}}",LIGHT_THEME_URL="{{light_theme_url|safe}}",DARK_THEME_URL="{{dark_theme_url|safe}}";</script>
        <script src="{% static 'index.min.js' %}"></script>
    {% endblock js %}

  </body>
</html>

search/templates/search/credits.html
{% extends 'search/base.html' %}



{% block body %}

<div class="row">
    <div class="col s12 m6 offset-m2 l6 offset-l3">

        <h5 class='center-align'>Credits</h5>
        <div class="row"></div>
        <p class='center-align snippet-color'>
            DevSearch uses many open source components. Below you will find the link to the code and license of each open source projects. 
            <br>
            We really appreciate the contribution of the developers of these projects to open source ❤️ 
        </p>
        <div class="row"></div>

        <div>
            {% for project_name, project_details in projects.items %}
                    <div class="card credits-card center-align" id="{{project_name}}">
                        <div class="card-content snippet">

                            <h6 class="credits-title"> {{project_name}} </h6>

                            <p class="search-snippet">
                                {{project_details.description}}

                                <div class="row"></div>

                                <div>
                                    <small> {{project_details.copyright}} </small>
                                </div>
                            </p>

                        </div>

                        <div class="card-action credits-action">
                            <a target="_blank" rel="noopener" class="no-margin btn-flat credits-button credits-action-link"   href="{{project_details.project_link}}">Project Link</a>
                            <a target="_blank" rel="noopener" class="no-margin btn-flat credits-button credits-action-link" href="{{project_details.license_link}}">
                                License 
                                <span class="snippet-color">  ({{project_details.license_type}})  </span> 
                            </a> 
                        </div>
                  </div>
            {% endfor %}

            <div class="row"></div>

            <div class="center-align">
                <a class="btn-small theme-button" href="/"> Go back to search </a>
            </div>
            

        </div>

    </div>
</div>




{% endblock body %}

search/templates/search/index.html
{% extends "search/base.html" %} 
{% load search_extras %}
{% block body %}    

    <div class="row">

        {% comment %} Search form {% endcomment %}
        <form method="GET" class="col s12 m10 offset-m1 l6 offset-l3">

            <h5 class="center-align major-mono"> 
            <a href="/">
                <span id="dev-heading">Dev</span><span id="remaining-heading">Search</span> </h5>
            </a>            
            <div class="row"></div>
            <div class="input-field z-depth-1" id="search-box">
                    <i id="search-icon" class="material-icons prefix">search</i>

                    <input
                        type="search"
                        id="search-field"
                        placeholder="Web, App, APIs"
                        name="q"
                        value="{{query}}"
                    />
            </div>
            {% if not query %}
                <div class="right-align ">
                    <button type="submit" class="rounded btn-small waves-effect theme-button" >Search</button>
                </div>
            {% endif %}

        </form>

        {% if query %}

            {% comment %} Results section {% endcomment %}

            <div id="results" class="col s12 m8 offset-m2 l6 offset-l3">

                    {% comment %} Tabs  {% endcomment %}
                    <ul class="tabs row">
                        {% for category in results.keys %}
                            <li class="tab m5 l5 xl2">
                                <a class="{{category}} {% if forloop.counter0 == 0  %} active {% endif %}"  
                                    href="#search-{{category|to_hyphens}}">
                                    {{category}}
                                </a>
                            </li>
                        {% endfor %} 
                    </ul>

                    {% comment %} Extra margin {% endcomment %}
                    <div class="row"></div>

                    {% comment %} Search results {% endcomment %}
                    {% for category, search_results in results.items %}
                        <div id="search-{{category|to_hyphens}}">
                            {% for item in search_results %}
                                        <div class="card search-card">
                                            <div class="card-content">
                                                <a href="{{item.link}}" rel="noopener" class="card-title search-title">{{item.title}}</a>
                                                <p><span class="search-link" >{{item.htmlFormattedUrl | safe}}</span></p>
                                                <p class="search-snippet">{{item.htmlSnippet | safe}}</p>
                                            </div>
                                        </div>
                                {% empty %} 

                                    {% comment %} if no results found and daily search limit is not reached {% endcomment %}
                                    {% if query and not limit_reached %}
                                        <div class="center-align grey-text text-darken-2">
                                            <div class="row"> 
                                                <i class="material-icons md-48">emoji_nature</i>
                                            </div>
                                            <div>
                                                <span class="light-text med-font">Nothing found </span>
                                            </div>
                                        </div>
                                        <div class="center-align grey-text text-darken-2">
                                            <span> 
                                                <small class="light-text">Try navigating to previous or next page</small>
                                            </span>
                                        </div>
                                        <div class="row"></div>
                                    
                                    {% comment %} if no results found and daily search limit is exceeded {% endcomment %}
                                    {% elif query and limit_reached %}
                                        <div class="center-align grey-text text-darken-2 no-margin">
                                            <div class="row">
                                                <i class="material-icons md-48">timelapse</i>
                                            </div>
                                            <div> 
                                                <span class="light-text med-font"> Search limit reached </span>
                                            </div>
                                             <div class="center-align grey-text text-darken-2">
                                               <span> 
                                                    <small class="light-text">Try searching after sometime</small>
                                                </span>
                                            </div>
                                        </div>
                                    {% endif %} 

                            {% endfor %}

                            <div>
                                {% if has_prev_page %}
                                    <div class="left">
                                        <a href="{{prev_page_url}}#search-{{category}}" 
                                            class="btn-small waves-effect rounded theme-button white-text transparent">
                                            <i class="material-icons left">arrow_back</i>
                                            <span>Previous</span>
                                        </a>
                                    </div>
                                {% endif %}

                                {% if has_next_page %}
                                    <div class="right">
                                        <a href="{{next_page_url}}#search-{{category}}" 
                                            class="btn-small waves-effect rounded theme-button white-text transparent">
                                            <span>Next</span>
                                            <i class="material-icons right">arrow_forward</i>
                                        </a>
                                    </div>
                                {% endif %}
                            </div>

                        </div>
                    {% endfor %}


                  
            </div>
        {% endif %}

    </div>
{% endblock body %}